APP = Demo
CC = g++
CC_FLAGS = -wall -wextra -pedantic
FRAMEWORKS = -framework GLUT -framework OpenGL
LIBS = -lGLEW

%.o: %.cpp
	$(CC) $(STANDARD) $(CC_FLAGS) -c $< 

all: Tokenizer.o Model.o Obj.o Driver.o
	$(CC) $(CC_FLAGS) $(FRAMEWORKS) $(LIBS) *.o -o $(APP)

clean:
	rm -f *.o $(APP)
